name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region:
          - name: 'thailand'
            url: 'https://download.geofabrik.de/asia/thailand-latest.osm.pbf'
          - name: 'india-central'
            url: 'https://download.geofabrik.de/asia/india/central-zone-latest.osm.pbf'
          - name: 'india-eastern'
            url: 'https://download.geofabrik.de/asia/india/eastern-zone-latest.osm.pbf'
          - name: 'india-north-eastern'
            url: 'https://download.geofabrik.de/asia/india/north-eastern-zone-latest.osm.pbf'
          - name: 'india-northern'
            url: 'https://download.geofabrik.de/asia/india/northern-zone-latest.osm.pbf'
          - name: 'india-southern'
            url: 'https://download.geofabrik.de/asia/india/southern-zone-latest.osm.pbf'
          - name: 'india-western'
            url: 'https://download.geofabrik.de/asia/india/western-zone-latest.osm.pbf'
          - name: 'indonesia-java'
            url: 'https://download.geofabrik.de/asia/indonesia/java-latest.osm.pbf'
          - name: 'indonesia-kalimantan'
            url: 'https://download.geofabrik.de/asia/indonesia/kalimantan-latest.osm.pbf'
          - name: 'indonesia-maluku'
            url: 'https://download.geofabrik.de/asia/indonesia/maluku-latest.osm.pbf'
          - name: 'indonesia-nusa-tenggara'
            url: 'https://download.geofabrik.de/asia/indonesia/nusa-tenggara-latest.osm.pbf'
          - name: 'indonesia-papua'
            url: 'https://download.geofabrik.de/asia/indonesia/papua-latest.osm.pbf'
          - name: 'indonesia-sulawesi'
            url: 'https://download.geofabrik.de/asia/indonesia/sulawesi-latest.osm.pbf'
          - name: 'indonesia-sumatra'
            url: 'https://download.geofabrik.de/asia/indonesia/sumatra-latest.osm.pbf'
          - name: 'zambia'
            url: 'https://download.geofabrik.de/africa/zambia-latest.osm.pbf'  
          - name: 'drc(usd)'
            url: 'https://download.geofabrik.de/africa/congo-democratic-republic-latest.osm.pbf'
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            OSM_FILE_URL=${{ matrix.region.url }}
            REGION_NAME=${{ matrix.region.name }}
          tags: |
            ghcr.io/${{ github.repository }}/osrm:${{ matrix.region.name }}-latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/osrm
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
