name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region:
          - name: 'thailand'
            url: 'https://download.geofabrik.de/asia/thailand-latest.osm.pbf'
          - name: 'central'
            url: 'https://download.geofabrik.de/asia/india/central-zone-latest.osm.pbf'
          - name: 'eastern'
            url: 'https://download.geofabrik.de/asia/india/eastern-zone-latest.osm.pbf'
          - name: 'north-eastern'
            url: 'https://download.geofabrik.de/asia/india/north-eastern-zone-latest.osm.pbf'
          - name: 'northern'
            url: 'https://download.geofabrik.de/asia/india/northern-zone-latest.osm.pbf'
          - name: 'southern'
            url: 'https://download.geofabrik.de/asia/india/southern-zone-latest.osm.pbf'      
          - name: 'western'
            url: 'https://download.geofabrik.de/asia/india/western-zone-latest.osm.pbf'                     
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            OSM_FILE_URL=${{ matrix.region.url }}
            REGION_NAME=${{ matrix.region.name }}
          tags: |
            ghcr.io/${{ github.repository }}/osrm-india:${{ matrix.region.name }}-latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/osrm-india
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
